name: Flutter Test

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths-ignore:
     - 'README.md'

  # Run tests for any PRs.
  pull_request:
    branches:
      - main
    paths-ignore:
     - 'README.md'
     
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
          
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.3'
          
      - name: Restore packages
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test
